### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#256]
The following tests may periodically fail

- synapse.tests.test_socket.SocketTest.test_sock_plex_txbuf
- synapse.tests.test_axon.AxonTest.test_axon_cluster
- synapse.tests.test_telepath.TelePathTest.test_telepath_push

Some remcycle tests may also fail as they may be relying on third party web services for integration tests.

**Comment by vEpiphyte** [comment]
```======================================================================
172s
1113
ERROR: test_axon_cluster (synapse.tests.test_axon.AxonTest)
172s
1114
----------------------------------------------------------------------
172s
1115
Traceback (most recent call last):
172s
1116
  File "/drone/src/github.com/vertexproject/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/tests/test_axon.py", line 272, in test_axon_cluster
172s
1117
    iden = axcluster.alloc(len(buf))
172s
1118
  File "/drone/src/github.com/vertexproject/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/axon.py", line 352, in alloc
172s
1119
    raise NoWritableAxons(bytag)
172s
1120
synapse.exc.NoWritableAxons: class.synapse.axon.Axon```

**Comment by vEpiphyte** [comment]
Socket test repro:
```n=0; while [[ $n -lt 10000 ]]; do nosetests --verbosity 3 -s --nologcapture synapse.tests.test_socket:SocketTest.test_sock_plex_txbuf; n=$((n+1)); done```

**Comment by vEpiphyte** [comment]
```======================================================================
ERROR: test_telepath_push (synapse.tests.test_telepath.TelePathTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/drone/src/github.com/vEpiphyte/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/tests/test_telepath.py", line 123, in test_telepath_push
    self.assertRaises( SynErr, prox1.bar, 10, 20 )
  File "/usr/local/lib/python3.4/unittest/case.py", line 707, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/local/lib/python3.4/unittest/case.py", line 162, in handle
    callable_obj(*args, **kwargs)
  File "/drone/src/github.com/vEpiphyte/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/telepath.py", line 161, in __call__
    return self.proxy.syncjob(job)
  File "/drone/src/github.com/vEpiphyte/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/telepath.py", line 367, in syncjob
    self._waitTeleJob(job,timeout=timeout)
  File "/drone/src/github.com/vEpiphyte/synapse/commit/5e8c27f024324f97650eff1fdd1234a18df89f2d/synapse/telepath.py", line 377, in _waitTeleJob
    raise HitMaxTime()
synapse.exc.HitMaxTime
```

**Comment by vEpiphyte** [comment]
this will eventually trigger a axon test failure
```
n=0; while [[ $n -lt 10000 ]];
    do nosetests --verbosity 3 -s --nologcapture synapse.tests.test_axon:AxonTest.test_axon_cluster;
    if [ $? -eq 0 ]; then
        n=$((n+1)); 
    else
        n=10000;
    fi
done
```

**Comment by vEpiphyte** [comment]
This will eventually trigger a telepath test failure ```n=0; while [[ $n -lt 10000 ]];
    do nosetests --verbosity 3 -s --nologcapture synapse.tests.test_telepath:TelePathTest.test_telepath_push;
    if [ $? -eq 0 ]; then
        n=$((n+1)); 
    else
        n=10000;
    fi
done```

**Comment by vEpiphyte** [comment]
synapse.tests.test_axon.AxonTest.test_axon_clusterd also experiences occasional failures

**Comment by vertexmc** [comment]
@vEpiphyte - are all of these fixed now?

**Comment by vEpiphyte** [comment]
@vertexmc I want to keep this open for a little bit longer.  We have some possible issues with remcycle tests and want to keep an eye open if we encounter other errors when bumping up the number of build agents.

**Comment by vertexmc** [comment]
Tracking Hypnos tests in https://github.com/vertexproject/synapse/issues/272
