### ISSUE TITLE
Check for yaml.CSafeLoader raises AttributeError

### ISSUE THREAD

**Issue by aaronst** [vertexproject/synapse#3383]
https://github.com/vertexproject/synapse/blob/fbc02f62d559a0463f09807833edb7356ae0f2b5/synapse/common.py#L64

It looks like this line might sometimes raise an `AttributeError`:

```
[pegasus (16:47) ~]
➜ source ~/.venv/synapse/bin/activate
(synapse) [pegasus (16:47) ~]
➜ python -V
Python 3.11.5
(synapse) [pegasus (16:47) ~]
➜ python -m synapse.servers.cortex --telepath ssl://synapse.hyperion.xnet:27492/ /synapse/cortex
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/schrodinger/.venv/synapse/lib/python3.11/site-packages/synapse/servers/cortex.py", line 5, in <module>
    import synapse.cortex as s_cortex
  File "/home/schrodinger/.venv/synapse/lib/python3.11/site-packages/synapse/cortex.py", line 13, in <module>
    import synapse.axon as s_axon
  File "/home/schrodinger/.venv/synapse/lib/python3.11/site-packages/synapse/axon.py", line 13, in <module>
    import synapse.common as s_common
  File "/home/schrodinger/.venv/synapse/lib/python3.11/site-packages/synapse/common.py", line 64, in <module>
    if Loader != yaml.CSafeLoader:  # pragma: no cover
                 ^^^^^^^^^^^^^^^^
AttributeError: module 'yaml' has no attribute 'CSafeLoader'. Did you mean: 'SafeLoader'?
(synapse) [pegasus (16:47) ~]
➜ pip freeze | grep -Ei '(synapse|yaml)'
PyYAML==6.0.1
synapse==2.151.0
```

**Comment by Cisphyx** [comment]
Closed by #3386
