### ISSUE TITLE
[BUG]  lib.inet.http.get connects via https instead of specified url protocol when a proxy is set.

### ISSUE THREAD

**Issue by jwahsnakupaku** [vertexproject/synapse#3708]
**Describe the bug**
When I specify a url to lib.inet.http.get, with a http proxy, it tries to connect via https instead of http.

**To Reproduce**
Specify http url with http proxy;
```
$lib.inet.http.get('http://netinfo.local/lookup?ip=1.1.1.1', proxy="http://webproxy.local:3128")
#SQUID Logs
1714709924.192      0 <Cortex IP> TCP_DENIED/403 3934 CONNECT netinfo.local:80 - HIER_NONE/- text/html
```

If I use Curl it works as expected
```
http_proxy=http://webproxy.local:3128 curl http://webproxy.local/lookup?ip=1.1.1.1
# SQUID Logs
1714709989.807      2 <CURL IP> TCP_MISS/200 681 GET http://netinfo.local/lookup? - HIER_DIRECT/<Netinfo IP> application/json
```
If I remove the proxy it'll work as expected, eg;
```$lib.inet.http.get('http://netinfo.local/lookup?ip=1.1.1.1'")```

If I use a https url it works;
```
$lib.inet.http.get('https://netinfo.local/lookup?ip=1.1.1.1', proxy="http://webproxy.local:3128")
# Squid Logs
1714710571.697     21 <Cortex IP>2 TCP_TUNNEL/200 3073 CONNECT netinfo.local:443 - HIER_DIRECT/<Netinfo IP> -
```
**Expected behavior**
$lib.inet.http.get tries HTTP instead of HTTPS..

**Environment (please complete the following information):**
 - OS: k8s
 - Synapse Version 2.165.0
 - Python Version 3.11
 - Output of `python -m pip freeze`
```
$ kubectl -n synapse exec -it deployment/aha -- python -m pip freeze
aiohttp==3.9.3
aiohttp-socks==0.8.4
aioimaplib==1.0.1
aiosignal==1.3.1
aiosmtplib==3.0.1
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
arrow==1.3.0
async-timeout==4.0.3
attrs==23.1.0
base58==2.1.1
beautifulsoup4==4.12.2
bech32==1.2.0
cattrs==23.1.2
cbor2==5.6.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
codecov==2.1.13
colorama==0.4.6
coverage==7.4.0
cpe==1.2.1
cryptography==42.0.5
exceptiongroup==1.2.0
execnet==2.0.2
fastjsonschema==2.19.1
fqdn==1.5.1
frozenlist==1.4.1
html5lib==1.1
idna==3.6
iniconfig==2.0.0
isoduration==20.11.0
jsonpointer==2.4
jsonschema==4.17.3
lark==1.1.9
lmdb==1.4.1
more-itertools==10.1.0
msgpack==1.0.8
multidict==6.0.4
oauthlib==3.2.2
packaging==23.2
platformdirs==4.1.0
pluggy==1.3.0
prompt-toolkit==3.0.43
pycodestyle==2.11.1
pycparser==2.21
pycryptodome==3.20.0
Pygments==2.17.2
pyOpenSSL==24.1.0
pyrsistent==0.19.3
pytest==7.4.3
pytest-cov==4.1.0
pytest-forked==1.6.0
python-bitcoinlib==0.12.2
python-dateutil==2.8.2
python-socks==2.4.4
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
requests-cache==1.1.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
scalecodec==1.2.7
simplejson==3.19.2
six==1.16.0
soupsieve==2.5
stix2-patterns==2.0.0
stix2-validator==3.1.4
synapse @ file:///build/synapse
toml==0.10.2
tomli==2.0.1
tornado==6.4
types-python-dateutil==2.8.19.14
typing_extensions==4.9.0
uri-template==1.3.0
url-normalize==1.4.3
urllib3==2.1.0
vcrpy==5.1.0
wcwidth==0.2.12
webcolors==1.13
webencodings==0.5.1
wrapt==1.15.0
xxhash==3.4.1
yarl==1.9.4
```

**Additional context**

**Comment by vEpiphyte** [comment]
@jwahsnakupaku Are there any exception logs on the Cortex when you attempt the first connection?

Can you share how your proxy is setup & configured?

**Comment by jwahsnakupaku** [comment]
Yeah, errors with 403 forbidden.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 118, in _connect
    await connector.connect(
  File "/usr/local/lib/python3.11/dist-packages/python_socks/_connectors/http_async.py", line 36, in connect
    reply: http.ConnectReply = conn.receive(data)
                               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/python_socks/_protocols/http.py", line 147, in receive
    return ConnectReply.loads(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/python_socks/_protocols/http.py", line 136, in loads
    raise ReplyError(msg, error_code=status_code)
python_socks._protocols.errors.ReplyError: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/synapse/lib/stormhttp.py", line 465, in _httpRequest
    async with sess.request(meth, url, headers=headers, **kwargs) as resp:
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp_socks/connector.py", line 85, in _wrap_create_connection
    stream = await proxy.connect(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 70, in connect
    return await self._connect(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 131, in _connect
    raise ProxyError(e, error_code=e.error_code)
python_socks._errors.ProxyError: 403 Forbidden
```

Squid is setup to only allow specific ports to connect, eg; `http_access deny CONNECT !SSL_ports`
If I add 80 to SSL_ports it'll work.

Guess I didn't expect http traffic to go via connect, if that's expected can probably close this.

**Comment by vEpiphyte** [comment]
The HTTP proxy implementation ( using aiotthp-socks & python-socks ) doesn't distinguish between HTTP / HTTPS - all traffic is routed through the configured proxy using a CONNECT statement. Can you try adding the expected HTTPS ports in your squid configuration?

**Comment by jwahsnakupaku** [comment]
Yes have confirmed that works, thanks for you help.
