### ISSUE TITLE
ingest_example[2-4].json exception - NoSuchForm: name='inet:netuser'

### ISSUE THREAD

**Issue by tn3rt** [vertexproject/synapse#594]
The examples ingest_example[2-4].json from the Ingest section of the User Guide raise an exception with the following traceback:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/tbrunson6/synapse/synapse/tools/ingest.py", line 163, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/home/tbrunson6/synapse/synapse/tools/ingest.py", line 146, in main
        gest.ingest(core)
      File "/home/tbrunson6/synapse/synapse/lib/ingest.py", line 372, in ingest
        self._ingEmbedInfo(core, embed, scope)
      File "/home/tbrunson6/synapse/synapse/lib/ingest.py", line 504, in _ingEmbedInfo
        node = core.formTufoByProp(form, valu)
      File "/home/tbrunson6/synapse/synapse/cores/common.py", line 2656, in formTufoByProp
        self.reqTufoForm(prop)
      File "/home/tbrunson6/synapse/synapse/datamodel.py", line 224, in reqTufoForm
        raise s_common.NoSuchForm(name=name)
    synapse.exc.NoSuchForm: NoSuchForm: name='inet:netuser'

The same message was produced in both an Ubuntu 16.04 installation and the Docker image.

**Comment by therealsilence** [comment]
Thanks for the catch - the inet:netuser form was migrated to inet:web:acct (see the code / model in inet.py). FYI until we can make the updates / corrections.

**Comment by vEpiphyte** [comment]
@tn3rt Thanks for this catch! We'll have the docs updated by the next release (v0.0.44)
